### ISSUE TITLE
您好，请问能分享一下数据库文件吗？

### ISSUE THREAD

**Issue by DeGuang1996** [c-rainstorm/OnlineShoppingSystem#8]
谢谢。

**Comment by c-rainstorm** [comment]
[建库 SQL](https://github.com/c-rainstorm/OnlineShoppingSystem-Documents/blob/master/%E9%9C%80%E6%B1%82%E4%B8%8E%E8%AE%BE%E8%AE%A1/create_reset_db.sql)

[项目所有文档](https://github.com/c-rainstorm/OnlineShoppingSystem-Documents)

代码写的一般，看看就好

**Comment by DeGuang1996** [comment]
感谢您的分享，膜拜dalao
